wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1680508098
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 13
      4: 3.9.5
      5: 0.12.21
      6: 4.15.0
      8:
      - 5
