wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.5
    start_time: 1680505672
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      - 12
      - 33
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 7
      - 13
      4: 3.9.5
      5: 0.12.21
      6: 4.15.0
      8:
      - 5
batch_size:
  desc: null
  value: 16
cfg:
  desc: null
  value: cfg/proj1.yaml
data_dir:
  desc: null
  value: data/
embedder:
  desc: null
  value: en_core_web_sm
epochs:
  desc: null
  value: 30
gpus:
  desc: null
  value: None
input_size:
  desc: null
  value: 96
lr:
  desc: null
  value: 0.001
min_lr:
  desc: null
  value: 5.0e-05
model_name:
  desc: null
  value: mlp_1k
momentum:
  desc: null
  value: 0.9
num_classes:
  desc: null
  value: 5
num_workers:
  desc: null
  value: 8
opt:
  desc: null
  value: adamw
sched:
  desc: null
  value: cosine
warmup_epochs:
  desc: null
  value: 3
warmup_lr:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.01
